project:
  type: website
  output-dir: docs

website:
  title: "cotas-uerj"
  navbar:
    left:
      - href: index.qmd
        text: Ingresso
      - conc.qmd
      - evas.qmd
      - perfil.qmd
      - ipa.qmd
      - inte.qmd
      - cr.qmd
      - geo.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual